### ISSUE TITLE
e2e error/Traceback printed

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#1109]
### Tasks

Also on successful passes there is: https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1096/6/pipeline/

```
Error while deleting rows: could not translate host name "db" to address: Name or service not known

Traceback (most recent call last):
  File "/home/jenkins/workspace/PermaplanT_PR-1096/e2e/clean_db.py", line 51, in <module>
    delete_maps_with_sut(dbname, user, password, host, port)
  File "/home/jenkins/workspace/PermaplanT_PR-1096/e2e/clean_db.py", line 47, in delete_maps_with_sut
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
```

**Comment by Bushuo** [comment]
Will be fixed with #1117
