### ISSUE TITLE
npm run storybook broken

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#439]
When running `npm run storybook` on master I see:

```

> permaplant@0.1.3 storybook
> storybook dev -p 6006

@storybook/cli v7.0.6

info => Starting manager..
WARN unable to find package.json for react-leaflet
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                          │
│   Storybook 7.0.6 for react-vite started                                                 │
│   2.15 s for manager and 6.07 s for preview                                              │
│                                                                                          │
│    Local:            http://localhost:6006/                                              │
│    On your network:  http://192.168.178.24:6006/                                         │
│                                                                                          │
│   A new version (7.0.20) is available!                                                   │
│                                                                                          │
│   Upgrade now: npx storybook@latest upgrade                                              │
│                                                                                          │
│   Read full changelog: https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md   │
│                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
WARN 🚨 Unable to index ./src/generated/docs/docs/modules/features_map_planning_store_MapStoreTypes.mdx:
WARN   Error: Unexpected character `` ` `` (U+0060) before name, expected a character that can start a name, such as a letter, `$`, or `_`
WARN     at /home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:2054
WARN     at async Promise.all (index 82)
WARN     at async Promise.all (index 0)
WARN     at async StoryIndexGenerator.updateExtracted (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:1601)
WARN     at async StoryIndexGenerator.ensureExtracted (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:2357)
WARN     at async StoryIndexGenerator.initialize (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:1528)

```

In the browser I see:

```
Oh no! Something went wrong loading this Storybook.

Unable to index ./src/generated/docs/docs/modules/features_map_planning_store_MapStoreTypes.mdx:
  Error: Unexpected character `` ` `` (U+0060) before name, expected a character that can start a name, such as a letter, `$`, or `_`
    at /home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:2054
    at async Promise.all (index 82)
    at async Promise.all (index 0)
    at async StoryIndexGenerator.updateExtracted (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:1601)
    at async StoryIndexGenerator.ensureExtracted (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:2357)
    at async StoryIndexGenerator.initialize (/home/markus/Projekte/PermaplanT/frontend/node_modules/@storybook/core-server/dist/index.js:13:1528)
```

**Comment by markus2330** [comment]
@Bushuo do you think this is a quick fix? Can someone help out here? Lets talk tomorrow.

**Comment by Bushuo** [comment]
@markus2330 Did you try it on the newest master branch and did you re-run `npm run doc`?
I thought that I fixed it with https://github.com/ElektraInitiative/PermaplanT/pull/466/commits/d216de541860b462409a44dcda49ed20f0a49ec8
forgot to mention this issue though.

I just tried again on master and it works on my machine.

**Comment by markus2330** [comment]
`npm i` did the trick for me. I am really not used that all target dependencies needs to be done by hand, looking forward to #549
